import { spawnSync } from 'node:child_process';
import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import process from 'node:process';
import { parse } from 'yaml';

const root = resolve(import.meta.dirname, '../..');
const sourcePath = resolve(root, 'firmware/config/recipes.yaml');
const targetPath = resolve(root, 'shared/calibration/recipe-catalog.generated.ts');

const slug = (value) =>
  value
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/['’]/g, '')
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_|_$/g, '');

const source = parse(await readFile(sourcePath, 'utf8'));
if (source?.version !== 1 || source?.units?.volume !== 'ml') {
  throw new Error('Unsupported recipe catalog version or volume unit');
}
if (!Array.isArray(source.recipes) || source.recipes.length !== 6) {
  throw new Error('The canonical calibration catalog must contain exactly six recipes');
}

const targetVolumeUl = Math.round(Number(source.target_pour_ml) * 1000);
const catalog = {
  schema: 'tnp.calibration.recipe-catalog.v1',
  sourceVersion: source.version,
  displayedDecimalPlaces: source.rounding.displayed_decimal_places,
  recipes: source.recipes.map((recipe) => ({
    recipeId: recipe.id,
    name: recipe.name,
    targetVolumeUl,
    ratioTotalParts: recipe.ratio_total_parts,
    ingredients: recipe.ingredients.map((ingredient) => ({
      ingredientId: slug(ingredient.name),
      name: ingredient.name,
      ratioParts: ingredient.ratio_parts,
      volumeUl: Math.round(Number(ingredient.volume_ml) * 1000),
    })),
  })),
};

const unformatted = `// Generated by \`pnpm calibration:recipes:generate\` from firmware/config/recipes.yaml.\n// Do not edit by hand.\nimport type { RecipeCatalogV1 } from './types';\n\nexport const RECIPE_CATALOG = ${JSON.stringify(catalog, null, 2)} as const satisfies RecipeCatalogV1;\n`;
const formatter = spawnSync(
  resolve(root, 'node_modules/.bin/biome'),
  ['format', '--stdin-file-path', targetPath],
  { input: unformatted, encoding: 'utf8' },
);
if (formatter.status !== 0) {
  throw new Error(`Biome could not format the generated catalog: ${formatter.stderr}`);
}
const generated = formatter.stdout;

if (process.argv.includes('--check')) {
  const existing = await readFile(targetPath, 'utf8');
  if (existing !== generated) {
    throw new Error('Generated recipe catalog is stale; run pnpm calibration:recipes:generate');
  }
} else {
  await writeFile(targetPath, generated);
}
