// Generated by `pnpm calibration:recipes:generate` from firmware/config/recipes.yaml.
// Do not edit by hand.
import type { RecipeCatalogV1 } from './types';

export const RECIPE_CATALOG = {
  schema: 'tnp.calibration.recipe-catalog.v1',
  sourceVersion: 1,
  displayedDecimalPlaces: 1,
  recipes: [
    {
      recipeId: 'california_negroni',
      name: 'California Negroni',
      targetVolumeUl: 200000,
      ratioTotalParts: 14,
      ingredients: [
        {
          ingredientId: 'st_george_gin',
          name: 'St. George Gin',
          ratioParts: 6,
          volumeUl: 85700,
        },
        {
          ingredientId: 'antica_formula_vermouth',
          name: 'Antica Formula Vermouth',
          ratioParts: 5,
          volumeUl: 71400,
        },
        {
          ingredientId: 'bruto_americano',
          name: 'Bruto Americano',
          ratioParts: 3,
          volumeUl: 42900,
        },
      ],
    },
    {
      recipeId: 'pony_espresso_martini',
      name: 'Pony Espresso Martini',
      targetVolumeUl: 200000,
      ratioTotalParts: 4,
      ingredients: [
        {
          ingredientId: 'hanger_one_vodka',
          name: 'Hanger One Vodka',
          ratioParts: 2,
          volumeUl: 100000,
        },
        {
          ingredientId: 'kahlua',
          name: 'Kahlua',
          ratioParts: 1,
          volumeUl: 50000,
        },
        {
          ingredientId: 'espresso',
          name: 'Espresso',
          ratioParts: 1,
          volumeUl: 50000,
        },
      ],
    },
    {
      recipeId: 'old_pal',
      name: 'Old Pal',
      targetVolumeUl: 200000,
      ratioTotalParts: 3,
      ingredients: [
        {
          ingredientId: 'michters_rye',
          name: "Michter's Rye",
          ratioParts: 1,
          volumeUl: 66700,
        },
        {
          ingredientId: 'antica_formula_vermouth',
          name: 'Antica Formula Vermouth',
          ratioParts: 1,
          volumeUl: 66700,
        },
        {
          ingredientId: 'bruto_americano',
          name: 'Bruto Americano',
          ratioParts: 1,
          volumeUl: 66700,
        },
      ],
    },
    {
      recipeId: 'mare_garita',
      name: 'Mare-garita',
      targetVolumeUl: 200000,
      ratioTotalParts: 13,
      ingredients: [
        {
          ingredientId: 'mescal',
          name: 'Mescal',
          ratioParts: 6,
          volumeUl: 92300,
        },
        {
          ingredientId: 'grand_marnier',
          name: 'Grand Marnier',
          ratioParts: 4,
          volumeUl: 61500,
        },
        {
          ingredientId: 'sour_mix',
          name: 'Sour mix',
          ratioParts: 3,
          volumeUl: 46200,
        },
      ],
    },
    {
      recipeId: 'moscow_mule',
      name: 'Moscow Mule',
      targetVolumeUl: 200000,
      ratioTotalParts: 7,
      ingredients: [
        {
          ingredientId: 'hanger_one_vodka',
          name: 'Hanger One Vodka',
          ratioParts: 2,
          volumeUl: 57100,
        },
        {
          ingredientId: 'ginger_beer',
          name: 'Ginger beer',
          ratioParts: 4,
          volumeUl: 114300,
        },
        {
          ingredientId: 'lime_juice',
          name: 'Lime juice',
          ratioParts: 1,
          volumeUl: 28600,
        },
      ],
    },
    {
      recipeId: 'kentucky_derby_julep',
      name: 'Kentucky Derby Julep',
      targetVolumeUl: 200000,
      ratioTotalParts: 5,
      ingredients: [
        {
          ingredientId: 'woodford_reserve',
          name: 'Woodford Reserve',
          ratioParts: 4,
          volumeUl: 160000,
        },
        {
          ingredientId: 'syrup',
          name: 'Syrup',
          ratioParts: 1,
          volumeUl: 40000,
        },
      ],
    },
  ],
} as const satisfies RecipeCatalogV1;
